steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args:
    - -c
    - docker build --build-arg WANDB_KEY=$$WANDB -t us-central1-docker.pkg.dev/tum-adlr-ws22-06/adlr/train_contrainer .
  #args: [ 'build', '.',  '--build-arg', 'WANDB_KEY=WANDB_KEY',  '-t', 'europe-docker.pkg.dev/tum-adlr-ws22-06/adlr/train_contrainer' ]
  secretEnv: ['WANDB']

images:
- 'us-central1-docker.pkg.dev/tum-adlr-ws22-06/adlr/train_contrainer'

availableSecrets:
  secretManager:
  - versionName: projects/612717574966/secrets/WANDB_KEY/versions/1
    env: 'WANDB'