defaults:
  - agent: ddpg
  - _self_

agent:
  experiment_name: "${agent.name}_default_env"

training:
  episodes: 1000
  episode_length: 1000
  exploration: 50
  train_batches: 1
  batch_size: 64
  min_replay_size: 1000
  replay_buffer_size: 1000000
  seed: 0
  noise: 'Gaussian' #'Zero','Gaussian', 'Ornstein'
  noise_param: 0.2

validation:
  eval_eps: 5
  eval_interval: 10
  render: False
  record_video_on_eval: True
  validation_episode_length: 1000
  log_actions: True

env:
  env: 'LunarLanderContinuous-v2'
  
  

