defaults:
  - agent: ddpg
  - _self_

agent:
  experiment_name: "${agent.name}_default_env"

training:
  episodes: 1000
  episode_length: 1000
  exploration: 50
  train_batches: 5
  batch_size: 256
  min_replay_size: 1000
  replay_buffer_size: 100000
  seed: 0

validation:
  eval_eps: 5
  eval_interval: 10
  render: False
  record_video_on_eval: True
  validation_episode_length: 1000
  log_actions: True

env:
  env: 'LunarLanderContinuous-v2'
  noise: True
  gaussian_noise: False
  noise_param: 0.2
  
  

