defaults:
  - _self_
  - agent: sac
  - optional training: ${agent}
  - optional validation: ${agent}


agent:
  experiment_name: "${agent.name}_default_env"

training:
  episodes: 1000
  episode_length: 1000
  update_after: 1000
  start_steps: 1000
  update_every: 1
  train_batches: 1
  batch_size: 64
  min_replay_size: 1000
  replay_buffer_size: 1000000
  seed: 0
  noise: 'Ornstein' #'Zero','Gaussian', 'Ornstein'
  noise_param: 0.2

validation:
  log_model_wandb: True
  log_model_every_training_batch: 1000
  eval_eps: 5
  eval_interval: 20
  render: False
  record_video_on_eval: True
  validation_episode_length: 1000
  log_actions: True

env:
  env: 'LunarLanderContinuous-v2'
  
  

