ddpg:
  episodes: 10000
  episode_length: 1000
  exploration: 50
  train_interval: 1
  eval_eps: 5
  eval_interval: 10
  batch_size: 64
  min_replay_size: 1000
  replay_buffer_size: 1000000
  pi_lr: 0.0001
  q_lr: 0.001
  gamma: 0.99
  tau: 0.005
  render: False
  gaussian_noise: False
  noise_param: 0.2
  seed: 0
  env: 'LunarLanderContinuous-v2'
  experiment_name: ddpg
  record_video_on_eval: True