meta_batch: 64
num_iterations: 100
num_train_steps_per_itr: 1000
num_initial_steps: 100
num_tasks_sample: 100
num_steps_prior: 100
num_steps_posterior: 100
num_extra_rl_steps_posterior: 100
num_evals: 10
num_steps_per_eval: 1000
batch_size: 1024
embedding_batch_size: 1024
embedding_mini_batch_size: 1024
max_path_length: 1000
discount: 0.99
replay_buffer_size: 1000000
reward_scale: 1
num_exp_traj_eval: 1
update_post_train: 1
eval_deterministic: True
save_replay_buffer: False
save_algorithm: False
save_environment: False
render_eval_paths: False
dump_eval_paths: False