meta_batch: 32 # number of tasks to average the gradient across 64

# num_steps_per_eval: 600  # nuumber of transitions to eval on
num_steps: 600
batch_size: 256 # number of transitions in the RL batch 1024
replay_buffer_size: 1000